# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:8.3.0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"    
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']  